version: '3.8'

services:
  app:
    image: henriqueasouza/products-api:latest
    ports:
      - '3030:3030'
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
  mongo:
    image: mongo:7.0.9
    volumes:
      - ./mongod.conf:/etc/mongo/mongod.conf
    ports:
      - 27017:27017
    restart: always
    command: --config /etc/mongo/mongod.conf
