version: '3.8'

services:
  mongo:
    image: mongo:7.0.9
    volumes:
      - ./mongod.conf:/etc/mongo/mongod.conf
    ports:
      - 27017:27017
    restart: always
    command: --config /etc/mongo/mongod.conf
